---

title: |
  Retrieve result
instructions: |
  See above for additional information.

max_points: 100
view_type: access.types.stdsync.createForm

fieldgroups:

  - title: ''

    fields:

    - key: login
      type: checkbox
      required: true
      title: Confirmation
      options:
        - label: |
            I confirm that I have finished the tasks and I want to retrieve my result from the external service.
          correct: true
          value: yes

lti: Grader
lti_aplus_get_and_post: true

container:
  image: apluslms/grade-python:3.11-4.9-4.9
  privileged: true
  enable_network: true
  mount: module01/grade
  cmd: /exercise/run.sh
